project:
  type: book
  output-dir: docs

book:
  title: "Literate Computing"
  author: "Dan MacLean"
  date: "May 2022"
  search: true
  downloads: [pdf]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - 02-r-markdown.qmd
    - 03-jupyter-notebooks.qmd
  appendices:
    - appendix.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
comments:
  hypothesis: true
